# Generated by Django 6.1 on 2026-09-19 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('designs', '0005_alter_category_options_category_image_file_and_more'),
        ('storage', '0003_create_cache_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('cta_label', models.CharField(blank=True, default='Try Now', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='designs.category')),
                ('image_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.storedfile')),
            ],
            options={
                'ordering': [models.OrderBy(models.F('priority'), nulls_last=True), '-created_at'],
            },
        ),
    ]
