# Generated by Django 6.1 on 2026-09-22 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='help_support_email',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='help_support_email_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='help_support_phone',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='help_support_phone_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='help_support_telegram',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='help_support_telegram_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='help_support_whatsapp',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='help_support_whatsapp_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
