# Generated by Django 6.1 on 2026-09-25 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0002_appsetting_help_support_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='app_version',
            field=models.CharField(blank=True, default='1.0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='maintenance_mode',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='min_supported_version',
            field=models.CharField(blank=True, default='1.0.0', max_length=50),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='registration_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
