# Generated by Django 6.1 on 2026-09-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0003_appsetting_app_version_appsetting_maintenance_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='google_login_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
