# Generated by Django 6.1 on 2026-09-27 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_settings', '0004_appsetting_google_login_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='appsetting',
            name='allowed_file_extensions',
            field=models.CharField(blank=True, default='pdf, zip, svg, dxf, dwg, nc, tap, gcode, cnc, plt, ai, eps', max_length=500),
        ),
        migrations.AddField(
            model_name='appsetting',
            name='allowed_image_extensions',
            field=models.CharField(blank=True, default='jpg, jpeg, png, webp, gif', max_length=255),
        ),
    ]
