# Generated by Django 6.1 on 2026-09-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_file',
            field=models.FileField(blank=True, null=True, upload_to='designs/files/'),
        ),
        migrations.AddField(
            model_name='design',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='designs/images/'),
        ),
        migrations.AlterField(
            model_name='design',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
    ]
