# Generated by Django 6.1 on 2026-09-18 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0002_design_design_file_design_image_and_more'),
        ('storage', '0002_storedfile_provider_storage_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.storedfile'),
        ),
    ]
