# Generated by Django 6.1 on 2026-09-19 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0003_design_image_file'),
        ('storage', '0002_storedfile_provider_storage_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_stored_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.storedfile'),
        ),
    ]
