# Generated by Django 6.1 on 2026-09-19 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0004_design_design_stored_file'),
        ('storage', '0003_create_cache_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': [models.OrderBy(models.F('priority'), nulls_last=True), 'label']},
        ),
        migrations.AddField(
            model_name='category',
            name='image_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='storage.storedfile'),
        ),
        migrations.AddField(
            model_name='category',
            name='priority',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
