# Generated by Django 6.1 on 2026-09-22 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0005_alter_category_options_category_image_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='design_type',
            field=models.CharField(choices=[('2d', '2D'), ('3d', '3D')], default='2d', max_length=2),
        ),
        migrations.AddField(
            model_name='design',
            name='is_paid',
            field=models.BooleanField(default=True),
        ),
    ]
