# Generated by Django 6.1 on 2026-09-23 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0006_design_design_type_design_is_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='design',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='design',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
