# Generated by Django 6.1 on 2026-09-27 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designs', '0008_designpurchase'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='designpurchase',
            name='one_purchase_per_design',
        ),
    ]
