# Generated by Django 6.1 on 2026-09-24 12:05

from django.db import migrations, models


def mark_existing_passwords(apps, schema_editor):
    """Every account that exists now was made with a password (the register
    endpoint), except any whose password was later made unusable - Django marks
    those with a leading "!". Those without one stay `password_set = False`."""
    User = apps.get_model('accounts', 'User')
    User.objects.exclude(password='').exclude(password__startswith='!').update(
        password_set=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='password_set',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(mark_existing_passwords, migrations.RunPython.noop),
    ]
